### PR TITLE
Reduce slab pressure for icbinn data and fix error message

### PR DESCRIPTION
**Pull request by rneilturner**

### CODE REVIEW

**Review by jandryuk — APPROVED** [review]
Thanks, LGTM.

The slab change is from the 32bit days, AFAICT.  I wonder if it is still needed with 64bit kernels?  Still, it should be okay to take.

Bryer is correct about python3, AFAICT.  SWIG is doing some #define-ing to assign PyString to PyBytes while python strings are PyUnicode.

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/22/builds/46): [$master-custom-46](https://openxt.ainfosec.com/OpenXT/auto/master/master-custom/46/)

**Comment by crogers1** [comment]
Looks like this one got lost for a bit. We can merge whenever.

**Comment by jandryuk** [comment]
Will merge soon.

**Pull request merged**
